server:
  port: 8082

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres?rewriteBatchedStatements=true
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 2
      max-active: 100
      min-idle: 5
      max-wait: 100

mybatis:
  mapper-locations: classpath:/mapper/*



