server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&socketTimeout=60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 100
      min-idle: 5
      max-wait: 100

mybatis:
  mapper-locations: classpath:/mapper/*
