# ??????
spring.datasource.ds01.url=jdbc:postgresql://localhost:5432/ds01
spring.datasource.ds01.username=postgres
spring.datasource.ds01.password=123456
spring.datasource.ds01.driver-class-name=org.postgresql.Driver

# ???????
spring.datasource.ds02.url=jdbc:postgresql://localhost:5432/ds01
spring.datasource.ds02.username=postgres
spring.datasource.ds02.password=123456
spring.datasource.ds02.driver-class-name=org.postgresql.Driver

# Druid?????
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=20
spring.datasource.druid.test-on-borrow=true
spring.datasource.druid.validation-query=SELECT 1



spring.main.allow-circular-references=true