server:
  port: 8080
  servlet:
    context-path: /demo
ratelimiter:
  limit-map: {"[/testLimit]": 1, "[/testLimit2]": 2}
  limit-switch: true

config:
  test:
    map-test: {key1: value1, key2: value2, key3: value3}
    map-test2:
      key4: value4
      key5: value5
      key6: value6
    list-test:
      - 1
      - 2
      - 3
    string-test:

config2:
  test:
    map-test: {key1: value1, key2: value2, key3: value3}
    map-test2:
      key4: value4
      key5: value5
      key6: value6
    list-test:
      - 1
      - 2
      - 3
    list-test2: 1,2,3
    string-test: 123